kernel:
  image: "mobylinux/kernel:4.9.x"
  cmdline: "console=ttyS0 page_poison=1"
init:
  - linuxkit/init:cbd7ae748f0a082516501a3e914fa0c924ee941e
  - mobylinux/runc:b0fb122e10dbb7e4e45115177a61a3f8d68c19a9
  - mobylinux/containerd:18eaf72f3f4f9a9f29ca1951f66df701f873060b
  - mobylinux/ca-certificates:eabc5a6e59f05aa91529d80e9a595b85b046f935
onboot:
  - name: sysctl
    image: "linuxkit/sysctl:225c52c2d6f04a040663bac84cabf81825027f64"
  - name: dhcpcd
    image: "linuxkit/dhcpcd:ae03169274d19fe8841314fa5a6fea3c61adbf4e"
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
  - name: metadata
    image: "linuxkit/metadata:a810b68fec9c9282cf096eed50605ddd6b2f3142"
    binds:
     - /dev:/dev
     - /var:/var
     - /tmp/etc/resolv.conf:/etc/resolv.conf
    net: host
    capabilities:
     - CAP_SYS_ADMIN
services:
  - name: rngd
    image: "mobylinux/rngd:3dad6dd43270fa632ac031e99d1947f20b22eec9"
  - name: prometheus
    image: "moby/prom-us-central1-f"
    binds:
      - /dev:/dev
      - /var/lib/misc:/data
    capabilities:
      - all
    net: host
trust:
  image:
    - mobylinux/kernel
outputs:
  - format: kernel+initrd
  - format: gcp
    project: docker4x
    bucket: rolf
    family: moby-demo
    replace: true
