kernel:
  image: "linuxkit/kernel-ima:4.11.1-"
  cmdline: "console=ttyS0 console=tty0 page_poison=1 ima_appraise=enforce_ns"
init:
  - linuxkit/init:b3740303f3d1e5689a84c87b7dfb48fd2a40a192
  - linuxkit/runc:3a4e6cbf15470f62501b019b55e1caac5ee7689f
  - linuxkit/containerd:b1766e4c4c09f63ac4925a6e4612852a93f7e73b
  - linuxkit/ca-certificates:75cf419fb58770884c3464eb687ec8dfc704169d
  - linuxkit/ima-utils:fe119c7dac08884f4144cd106dc279ddd8b37517
onboot:
  - name: sysctl
    image: "linuxkit/sysctl:b16a483897dd5f71be7e0c04cd090b05f52682e1"
  - name: binfmt
    image: "linuxkit/binfmt:eb3977596d5fc9e847eee1d34cb3beb3f574cac9"
  - name: dhcpcd
    image: "linuxkit/dhcpcd:7d2f17a0e5d1ef9a75a527821a9ab0d753b22e7e"
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
services:
  - name: rngd
    image: "linuxkit/rngd:b67c3151a52b05db50e6207b40876900f2208d14"
  - name: nginx
    image: "nginx:alpine"
    capabilities:
     - CAP_NET_BIND_SERVICE
     - CAP_CHOWN
     - CAP_SETUID
     - CAP_SETGID
     - CAP_DAC_OVERRIDE
    net: host
files:
  - path: etc/docker/daemon.json
    contents: '{"debug": true}'
trust:
  image:
    - linuxkit/kernel
    - linuxkit/init
    - linuxkit/runc
    - linuxkit/containerd
    - linuxkit/ca-certificates
    - linuxkit/sysctl
    - linuxkit/binfmt
    - linuxkit/dhcpcd
    - linuxkit/rngd
