kernel:
  image: "linuxkit/kernel:4.9.x"
  cmdline: "console=ttyS0 page_poison=1"
init:
  - linuxkit/init:cbd7ae748f0a082516501a3e914fa0c924ee941e
  - linuxkit/runc:24dfe632ed3ff53a026ee3fac046fd544434e2d6
  - linuxkit/containerd:f1130450206d4f64f0ddc13d15bb68435aa1ff61
services:
  - name: rngd
    image: "linuxkit/rngd:69f951ce2a3a9534dbbc7ba8119e1df4391f06c0"
  - name: dhcpcd
    image: "linuxkit/dhcpcd:ae03169274d19fe8841314fa5a6fea3c61adbf4e"
  - name: node_exporter
    image: "linuxkit/node_exporter:bdb20b41855d0e2b4edeec44ef569d030ea3cc47"
    capabilities:
     - all
    net: host
    pid: host
    binds:
     - /proc:/host/proc
     - /sys:/host/sys
     - /:/rootfs
trust:
  image:
    - linuxkit/kernel
    - linuxkit/rngd
