kernel:
  image: "linuxkit/kernel:4.9.x"
  cmdline: "console=ttyS1 page_poison=1"
init:
  - linuxkit/init:deea956a9ab07bf262083e93a86930bdc610cc2f
  - linuxkit/runc:2649198589ef0020d99f613adaeda45ce0093a38
  - linuxkit/containerd:cf2614f5a96c569a0bd4bd54e054a65ba17d167f
  - linuxkit/ca-certificates:3344cdca1bc59fdfa17bd7f0fcbf491b9dbaa288
onboot:
  - name: sysctl
    image: "linuxkit/sysctl:1f5ec5d5e6f7a7a1b3d2ff9dd9e36fd6fb14756a"
    net: host
    pid: host
    ipc: host
    capabilities:
     - CAP_SYS_ADMIN
services:
  - name: rngd
    image: "linuxkit/rngd:61a07ced77a9747708223ca16a4aec621eacf518"
    capabilities:
     - CAP_SYS_ADMIN
    oomScoreAdj: -800
  - name: dhcpcd
    image: "linuxkit/dhcpcd:2def74ab3f9233b4c09ebb196ba47c27c08b0ed8"
    binds:
     - /var:/var
     - /tmp:/etc
    capabilities:
     - CAP_NET_ADMIN
     - CAP_NET_BIND_SERVICE
     - CAP_NET_RAW
    net: host
    oomScoreAdj: -800
  - name: sshd
    image: "linuxkit/sshd:e108d208adf692c8a0954f602743e0eec445364e"
    capabilities:
     - all
    net: host
    pid: host
    binds:
     - /root/.ssh:/root/.ssh
     - /etc/resolv.conf:/etc/resolv.conf
trust:
  image:
    - linuxkit/kernel
    - linuxkit/rngd
files:
  - path: root/.ssh/authorized_keys
    contents: '#your ssh key here'
outputs:
  - format: kernel+initrd
