kernel:
  image: "linuxkit/kernel:4.9.x"
  cmdline: "console=ttyS0 console=tty0 page_poison=1"
init:
  - linuxkit/init:1b8a7e394d2ec2f1fdb4d67645829d1b5bdca037
  - linuxkit/runc:2649198589ef0020d99f613adaeda45ce0093a38
  - linuxkit/containerd:b1766e4c4c09f63ac4925a6e4612852a93f7e73b
  - linuxkit/ca-certificates:75cf419fb58770884c3464eb687ec8dfc704169d
onboot:
  - name: sysctl
    image: "linuxkit/sysctl:3aa6bc663c2849ef239be7d941d3eaf3e6fcc018"
  - name: dhcpcd
    image: "linuxkit/dhcpcd:7d2b8aaaf20c24ad7d11a5ea2ea5b4a80dc966f1"
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
  - name: format
    image: "linuxkit/format:180cb2dc1de5e60373385080f8148abf10a3afac"
  - name: mount
    image: "linuxkit/mount:ff5338822f20375b8913f5a80f9ed4f6ea9a592b"
    command: ["/mount.sh", "/var/lib/swarmd"]
  - name: metadata
    image: "linuxkit/metadata:4e73345cdcb4f7e9df07b0ee7aede652960297f2"
services:
  - name: rngd
    image: "linuxkit/rngd:1fa4de44c961bb5075647181891a3e7e7ba51c31"
  - name: ntpd
    image: "linuxkit/openntpd:45deeb05f736162d941c9bf494983f655ab80aa5"
  - name: swarmd
    image: "linuxkit/swarmd:a2f57f14f07fb6d7cded7832b2dabe878b28554e"
    command: ["/usr/bin/swarmd", "--containerd-addr=/run/containerd/containerd.sock", "--log-level=debug", "--state-dir=/var/lib/swarmd"]
    capabilities:
     - CAP_CHOWN
     - CAP_DAC_OVERRIDE
     - CAP_FSETID
     - CAP_FOWNER
     - CAP_MKNOD
     - CAP_NET_RAW
     - CAP_SETGID
     - CAP_SETUID
     - CAP_SETFCAP
     - CAP_SETPCAP
     - CAP_NET_BIND_SERVICE
     - CAP_SYS_CHROOT
     - CAP_KILL
     - CAP_AUDIT_WRITE
    pid: host
    net: host
    binds:
      - /run/containerd/containerd.sock:/run/containerd/containerd.sock
      - /var/lib/containerd:/var/lib/containerd
      - /var/lib/swarmd:/var/lib/swarmd
      - /etc/resolv.conf:/etc/resolv.conf
